### PR TITLE
Allow disks to be specified for each ring type

### PR DESCRIPTION
**Pull request by ryshah**
Fix the issue #4

### CODE REVIEW

**Comment by ryshah** [comment]
@j2sol @craigtracey Please review the pull request. Proposed new schema for ring_definition. Open to suggestions. Once schema is approved, I will create PR in ursula to update envs/swift/ring_definition.yml

**Comment by omgjlk** [comment]
I think this looks okay.  @craigtracey ?

**Comment by ryshah** [comment]
@craigtracey Any thoughts on getting this merged? We would like this sooner rather than later

**Comment by scoop206** [comment]
:+1: 
We ran into the lack of services starting just last week and the ring work is a nice addition (and the documentation is much appreciated).

**Comment by ryshah** [comment]
@sandfish8 I had separate PR for starting services automatically. I closed it to investigate if that could be handled in ursula. I will re-open that PR for your reference (https://github.com/blueboxgroup/swifttool/pull/3)

**Comment by ryshah** [comment]
Closing this pull request due to merge issues

**Comment by ryshah** [comment]
Incorporated changes suggested by @craigtracey for backward compatibility

**Comment by omgjlk** [comment]
This looks good to me, and shouldn't break any of our existing swift deployments.

**Pull request merged**
